package Ventanas;

import clases.ManipulaBD;
import clases.Proveedores;
import java.util.ArrayList;

/**
 *
 * @author 
 */
public class Consultas_Proveedores extends javax.swing.JFrame
{

    public static ArrayList<Proveedores> provedor;

    /**
     * Creates new form Consultas_Proveedores
     */
    public Consultas_Proveedores()
    {
        initComponents();

        if (InicioSesion.usuario.get(0).getClasificacion() == 3)
        {
            BModifica.setEnabled(false);
        } else
        {
            BModifica.setEnabled(true);
        }

        String condicion = "-1";
        provedor = ManipulaBD.ConsultasProveedores("id!=", condicion);
        Actualizar();

    }

    public void Actualizar()
    {
        Object[][] matriz = new Object[provedor.size()][10];

        for (int i = 0; i < provedor.size(); i++)
        {
            matriz[i][0] = provedor.get(i).getNombre();
            matriz[i][1] = provedor.get(i).getApellidoP();
            matriz[i][2] = provedor.get(i).getApellidoM();
            matriz[i][3] = provedor.get(i).getRfc();
            matriz[i][4] = provedor.get(i).getRazon_Social();
            matriz[i][5] = provedor.get(i).getDireccion();
            matriz[i][6] = provedor.get(i).getCp();
            matriz[i][7] = provedor.get(i).getTelefono();
            matriz[i][8] = provedor.get(i).getEmail();
            matriz[i][9] = provedor.get(i).isEstatus();
        }

        TProveedores.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]
        {
            "Nombre", "ApellidoP", "ApellidoM", "RFC", "Razón Social", "Direccion", "CP", "Telefono", "Email", "Estatus"
        })
        {
            Class[] types = new Class[]
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class,
                java.lang.String.class, java.lang.String.class, java.lang.String.class,
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class,
                java.lang.Boolean.class
            };

            /*
            Cuales columnas pueden ser modificadas
             */
            boolean[] canEdit = new boolean[]
            {
                true, true, true,
                true, true, true,
                true
            };

            @Override
            public Class getColumnClass(int columnIndex)
            {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit[columnIndex];
            }
        }
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        TProveedores = new javax.swing.JTable();
        Bregresar = new javax.swing.JButton();
        BModifica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(TProveedores);

        Bregresar.setText("Regresar");
        Bregresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BregresarActionPerformed(evt);
            }
        });

        BModifica.setText("Modificar");
        BModifica.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BModificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bregresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BModifica)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bregresar)
                    .addComponent(BModifica))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BregresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BregresarActionPerformed
    {//GEN-HEADEREND:event_BregresarActionPerformed
        switch (InicioSesion.usuario.get(0).getClasificacion())
        {
            case 1:
                new Menu_Gerente().setVisible(true);
                break;
            case 2:
                new Menu_SubGerente().setVisible(true);
                break;
            case 3:
                new Menu_Empleado().setVisible(true);
                break;
        }
        this.setVisible(false);
    }//GEN-LAST:event_BregresarActionPerformed

    private void BModificaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BModificaActionPerformed
    {//GEN-HEADEREND:event_BModificaActionPerformed

        for (int i = 0; i < provedor.size(); i++)
        {

            boolean estatus = (boolean) TProveedores.getValueAt(i, 9);
            if (!estatus)
            {
                ManipulaBD.BajasProveedore(provedor.get(i).getId());
            } else
            {
                ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "nombre", "'" + TProveedores.getValueAt(i, 0) + "'");
                ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "apellidoP", "'" + TProveedores.getValueAt(i, 1) + "'");
                ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "apellidoM", "'" + TProveedores.getValueAt(i, 2) + "'");
                ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "rfc", "'" + TProveedores.getValueAt(i, 3) + "'");
                ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "razon_Social", "'" + TProveedores.getValueAt(i, 4) + "'");
                ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "direccion", "'" + TProveedores.getValueAt(i, 5) + "'");
                ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "cp", "'" + TProveedores.getValueAt(i, 6) + "'");
                ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "telefono", "'" + TProveedores.getValueAt(i, 7) + "'");
                ManipulaBD.ModificarProveedores(provedor.get(i).getId(), "email", "'" + TProveedores.getValueAt(i, 8) + "'");
            }
        }
        Actualizar();
    }//GEN-LAST:event_BModificaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Consultas_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Consultas_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Consultas_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Consultas_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Consultas_Proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BModifica;
    private javax.swing.JButton Bregresar;
    private javax.swing.JTable TProveedores;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
