/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import clases.ManipulaBD;
import clases.Productos;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class Consultas_Productos extends javax.swing.JFrame
{

    public static ArrayList<Productos> prod;

    /**
     * Creates new form Consultas_Productos
     */
    public Consultas_Productos()
    {
        initComponents();

        if (InicioSesion.usuario.get(0).getClasificacion() == 3)
        {
            BModifica.setEnabled(false);
        } else
        {
            BModifica.setEnabled(true);
        }

        String condicion = "-1";
        prod = ManipulaBD.ConsultasProductos("id!=", condicion);
        Actualizar();
    }

    public void Actualizar()
    {
        Object matriz[][] = new Object[prod.size()][13];
        for (int i = 0; i < prod.size(); i++)
        {
            matriz[i][0] = prod.get(i).getId_Proveedor();
            matriz[i][1] = prod.get(i).getCodigo();
            matriz[i][2] = prod.get(i).getNombre();
            matriz[i][3] = prod.get(i).getDescripcion();
            matriz[i][4] = prod.get(i).getPrecio_Venta();
            matriz[i][5] = prod.get(i).getPrecio_Compra();
            matriz[i][6] = prod.get(i).isPerecedero();
            matriz[i][7] = prod.get(i).getCantidad();
            matriz[i][8] = prod.get(i).getPeso();
            matriz[i][9] = prod.get(i).getCaducidad();
            matriz[i][10] = prod.get(i).getMarca();
            matriz[i][11] = prod.get(i).isEstatus();
            matriz[i][12] = prod.get(i).isExistencias();
        }

        TProd.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]
        {
            "Proveedor", "Codigo", "Nombre",
            "Descripcion", "Venta", "Compra",
            "Perecedero", "Cantidad", "Peso",
            "Caducidad", "Marca", "Estatus",
            "Existencia"
        })
        {
            /*
            Las clases de cada propiedad para tener un nivel de validación
             */
            Class[] types = new Class[]
            {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class,
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class,
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.Float.class,
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class,
                java.lang.Boolean.class
            };

            /*
            Cuales columnas pueden ser modificadas
             */
            boolean[] canEdit = new boolean[]
            {
                false, true, true,
                true, false, true,
                true, true, true,
                true, true, true,
                true
            };

            @Override
            public Class getColumnClass(int columnIndex)
            {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit[columnIndex];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        TProd = new javax.swing.JTable();
        Bregresar = new javax.swing.JButton();
        BModifica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(TProd);

        Bregresar.setText("Regresar");
        Bregresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BregresarActionPerformed(evt);
            }
        });

        BModifica.setText("Modificar");
        BModifica.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BModificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bregresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BModifica)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bregresar)
                    .addComponent(BModifica))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BregresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BregresarActionPerformed
    {//GEN-HEADEREND:event_BregresarActionPerformed
        switch (InicioSesion.usuario.get(0).getClasificacion())
        {
            case 1:
                new Menu_Gerente().setVisible(true);
                break;
            case 2:
                new Menu_SubGerente().setVisible(true);
                break;
            case 3:
                new Menu_Empleado().setVisible(true);
                break;
        }
        this.setVisible(false);
    }//GEN-LAST:event_BregresarActionPerformed

    private void BModificaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BModificaActionPerformed
    {//GEN-HEADEREND:event_BModificaActionPerformed

        for (int i = 0; i < prod.size(); i++)
        {
            if (TProd.getValueAt(i, 9).toString().matches("^([0-2][0-9]|3[0-1])(\\/|-)(0[1-9]|1[0-2])\\2(\\d{4})$"))
            {
                boolean perecedero = (boolean) TProd.getValueAt(i, 6);
                boolean estatus = (boolean) TProd.getValueAt(i, 11);

                if (!estatus)
                {
                    ManipulaBD.BajasProductos(prod.get(i).getId());
                } else
                {
                    boolean existecias = (boolean) TProd.getValueAt(i, 12);
                    String estatusP = String.valueOf(perecedero);
                    String estatusE = String.valueOf(existecias);
                    ManipulaBD.ModificarProductos(prod.get(i).getId(), "id_Proveedor", "" + TProd.getValueAt(i, 0) + "");
                    ManipulaBD.ModificarProductos(prod.get(i).getId(), "codigo", "" + TProd.getValueAt(i, 1) + "");
                    ManipulaBD.ModificarProductos(prod.get(i).getId(), "nombre", "'" + TProd.getValueAt(i, 2) + "'");
                    ManipulaBD.ModificarProductos(prod.get(i).getId(), "descripcion", "'" + TProd.getValueAt(i, 3) + "'");
                    ManipulaBD.ModificarProductos(prod.get(i).getId(), "precio_Venta", "" + TProd.getValueAt(i, 4) + "");
                    ManipulaBD.ModificarProductos(prod.get(i).getId(), "precio_Compra", "" + TProd.getValueAt(i, 5) + "");
                    ManipulaBD.ModificarProductos(prod.get(i).getId(), "perecedero", "'" + estatusP + "'");
                    ManipulaBD.ModificarProductos(prod.get(i).getId(), "cantidad", "" + TProd.getValueAt(i, 7) + "");
                    ManipulaBD.ModificarProductos(prod.get(i).getId(), "peso", "" + TProd.getValueAt(i, 8) + "");
                    ManipulaBD.ModificarProductos(prod.get(i).getId(), "caducidad", "'" + TProd.getValueAt(i, 9) + "'");
                    ManipulaBD.ModificarProductos(prod.get(i).getId(), "marca", "'" + TProd.getValueAt(i, 10) + "'");
                    ManipulaBD.ModificarProductos(prod.get(i).getId(), "existencias", "'" + estatusE + "'");
                }
            } else
            {
                JOptionPane.showMessageDialog(rootPane, "Error en la fecha");
                break;
            }
        }
        Actualizar();

    }//GEN-LAST:event_BModificaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Consultas_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Consultas_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Consultas_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Consultas_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Consultas_Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BModifica;
    private javax.swing.JButton Bregresar;
    private javax.swing.JTable TProd;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
